<div class="contenedor-formulario">
    <form action="editarItem/<?=$idproducto?>" method="POST">
        <div class="mb-3">
            <h6>Modificar precio</h6>

            <label for="nuevo">Nuevo precio:</label>
            <input name="nuevaImagen" placeholder="ingrese el nuevo precio" type="number" class="form-control form-add-cattegoria" aria-describedby="emailHelp">

            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </div>
    </form>
</div>