<a href='home' type="button" class="btn btn-info">Volver</a>

<div class="card mb-3 individualCard">
  <img src="<?=$producto->imagen?>" class="card-img-top" alt="Imagen del producto">
  <div class="card-body">
    <h5 class="card-title"><?=$producto->nombre?></h5>
    <p class="card-text">Material: <?=$producto->material?></p>
    <p class="card-text">Precio: <?=$producto->precio?></p>
    <p class="card-text">Categoría: <?=$categoriaProducto->tipo?></p>
  </div>
</div>