
<?php require './templates/header.phtml' ?>

<div class='divLogin'>
  <form action='auth' method='POST'>
    <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="email" class="form-control" name="email" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Contraseña</label>
      <input type="password" class="form-control" name="password">
    </div>

    <?php if ($error): ?>
      <div class="alert alert-danger" role="alert">
        <?=$error?>
      </div>
    <?php endif ?>

    <button type="submit" class="btn btn-primary">Ingresar</button>
  </form>
</div>


<?php require './templates/footer.phtml' ?>