<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Mueblería</title>
</head>
<body>
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <div class="d-flex align-items-center mb-3 mb-md-0 me-md-auto">
            <h1 class="fs-2">Amueblarte</h1>
        </div>

        <nav class="nav nav-pills">
            <a class="nav-item"><a href="login" class="nav-link active" aria-current="page">Login</a>
            <a class="nav-item"><a href="home" class="nav-link">Home</a>
            <a class="nav-item"><a href="auth" class="nav-link">Administración</a>         
        </nav>
        </header>
    </div>

    <main class="container mt-3">