<?php require './templates/header.phtml' ?>

<div class='login'>
  <form action='login' method='POST'>
    <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="email" class="form-control" id="email" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Contraseña</label>
      <input type="password" class="form-control" id="password">
    </div>
    <button type="submit" class="btn btn-primary">Ingresar</button>
  </form>
</div>


<?php require './templates/footer.phtml' ?>